sonar.verbose=true
sonar.organization=rakesh01-mykey
sonar.projectKey=rakesh01-mykey_rakeshproj1
sonar.projectName=rakeshproj1
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
